name: Scheduled Build and Test

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow every day at midnight

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8'  

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build src/src.sln --no-restore

    - name: Test
      run: dotnet test src/tests